package com.guilin.mycompose.ui.theme.color
import androidx.compose.ui.graphics.Color

val red_light_primary = Color(0xFFC0001B)
val red_light_onPrimary = Color(0xFFFFFFFF)
val red_light_primaryContainer = Color(0xFFFFDAD6)
val red_light_onPrimaryContainer = Color(0xFF410003)
val red_light_secondary = Color(0xFF775653)
val red_light_onSecondary = Color(0xFFFFFFFF)
val red_light_secondaryContainer = Color(0xFFFFDAD6)
val red_light_onSecondaryContainer = Color(0xFF2C1513)
val red_light_tertiary = Color(0xFF725B2E)
val red_light_onTertiary = Color(0xFFFFFFFF)
val red_light_tertiaryContainer = Color(0xFFFFDEA6)
val red_light_onTertiaryContainer = Color(0xFF261900)
val red_light_error = Color(0xFFBA1A1A)
val red_light_errorContainer = Color(0xFFFFDAD6)
val red_light_onError = Color(0xFFFFFFFF)
val red_light_onErrorContainer = Color(0xFF410002)
val red_light_background = Color(0xFFFFFBFF)
val red_light_onBackground = Color(0xFF201A19)
val red_light_surface = Color(0xFFFFFBFF)
val red_light_onSurface = Color(0xFF201A19)
val red_light_surfaceVariant = Color(0xFFF5DDDB)
val red_light_onSurfaceVariant = Color(0xFF534342)
val red_light_outline = Color(0xFF857371)
val red_light_inverseOnSurface = Color(0xFFFBEEEC)
val red_light_inverseSurface = Color(0xFF362F2E)
val red_light_inversePrimary = Color(0xFFFFB3AD)
val red_light_shadow = Color(0xFF000000)
val red_light_surfaceTint = Color(0xFFC0001B)
val red_light_outlineVariant = Color(0xFFD8C2BF)
val red_light_scrim = Color(0xFF000000)

val red_dark_primary = Color(0xFFFFB3AD)
val red_dark_onPrimary = Color(0xFF680009)
val red_dark_primaryContainer = Color(0xFF930012)
val red_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val red_dark_secondary = Color(0xFFE7BDB9)
val red_dark_onSecondary = Color(0xFF442927)
val red_dark_secondaryContainer = Color(0xFF5D3F3D)
val red_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val red_dark_tertiary = Color(0xFFE1C28C)
val red_dark_onTertiary = Color(0xFF402D04)
val red_dark_tertiaryContainer = Color(0xFF584319)
val red_dark_onTertiaryContainer = Color(0xFFFFDEA6)
val red_dark_error = Color(0xFFFFB4AB)
val red_dark_errorContainer = Color(0xFF93000A)
val red_dark_onError = Color(0xFF690005)
val red_dark_onErrorContainer = Color(0xFFFFDAD6)
val red_dark_background = Color(0xFF201A19)
val red_dark_onBackground = Color(0xFFEDE0DE)
val red_dark_surface = Color(0xFF201A19)
val red_dark_onSurface = Color(0xFFEDE0DE)
val red_dark_surfaceVariant = Color(0xFF534342)
val red_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val red_dark_outline = Color(0xFFA08C8A)
val red_dark_inverseOnSurface = Color(0xFF201A19)
val red_dark_inverseSurface = Color(0xFFEDE0DE)
val red_dark_inversePrimary = Color(0xFFC0001B)
val red_dark_shadow = Color(0xFF000000)
val red_dark_surfaceTint = Color(0xFFFFB3AD)
val red_dark_outlineVariant = Color(0xFF534342)
val red_dark_scrim = Color(0xFF000000)


val red_seed = Color(0xFFEF0024)
