package com.guilin.mycompose.ui.theme.color
import androidx.compose.ui.graphics.Color

val purple_light_primary = Color(0xFF6750A4)
val purple_light_onPrimary = Color(0xFFFFFFFF)
val purple_light_primaryContainer = Color(0xFFEADDFF)
val purple_light_onPrimaryContainer = Color(0xFF21005D)
val purple_light_secondary = Color(0xFF625B71)
val purple_light_onSecondary = Color(0xFFFFFFFF)
val purple_light_secondaryContainer = Color(0xFFE8DEF8)
val purple_light_onSecondaryContainer = Color(0xFF1D192B)
val purple_light_tertiary = Color(0xFF7D5260)
val purple_light_onTertiary = Color(0xFFFFFFFF)
val purple_light_tertiaryContainer = Color(0xFFFFD8E4)
val purple_light_onTertiaryContainer = Color(0xFF31111D)
val purple_light_error = Color(0xFFB3261E)
val purple_light_onError = Color(0xFFFFFFFF)
val purple_light_errorContainer = Color(0xFFF9DEDC)
val purple_light_onErrorContainer = Color(0xFF410E0B)
val purple_light_outline = Color(0xFF79747E)
val purple_light_background = Color(0xFFFFFBFE)
val purple_light_onBackground = Color(0xFF1C1B1F)
val purple_light_surface = Color(0xFFFFFBFE)
val purple_light_onSurface = Color(0xFF1C1B1F)
val purple_light_surfaceVariant = Color(0xFFE7E0EC)
val purple_light_onSurfaceVariant = Color(0xFF49454F)
val purple_light_inverseSurface = Color(0xFF313033)
val purple_light_inverseOnSurface = Color(0xFFF4EFF4)
val purple_light_inversePrimary = Color(0xFFD0BCFF)
val purple_light_shadow = Color(0xFF000000)
val purple_light_surfaceTint = Color(0xFF6750A4)
val purple_light_outlineVariant = Color(0xFFCAC4D0)
val purple_light_scrim = Color(0xFF000000)

val purple_dark_primary = Color(0xFFD0BCFF)
val purple_dark_onPrimary = Color(0xFF381E72)
val purple_dark_primaryContainer = Color(0xFF4F378B)
val purple_dark_onPrimaryContainer = Color(0xFFEADDFF)
val purple_dark_secondary = Color(0xFFCCC2DC)
val purple_dark_onSecondary = Color(0xFF332D41)
val purple_dark_secondaryContainer = Color(0xFF4A4458)
val purple_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val purple_dark_tertiary = Color(0xFFEFB8C8)
val purple_dark_onTertiary = Color(0xFF492532)
val purple_dark_tertiaryContainer = Color(0xFF633B48)
val purple_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val purple_dark_error = Color(0xFFF2B8B5)
val purple_dark_onError = Color(0xFF601410)
val purple_dark_errorContainer = Color(0xFF8C1D18)
val purple_dark_onErrorContainer = Color(0xFFF9DEDC)
val purple_dark_outline = Color(0xFF938F99)
val purple_dark_background = Color(0xFF1C1B1F)
val purple_dark_onBackground = Color(0xFFE6E1E5)
val purple_dark_surface = Color(0xFF1C1B1F)
val purple_dark_onSurface = Color(0xFFE6E1E5)
val purple_dark_surfaceVariant = Color(0xFF49454F)
val purple_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val purple_dark_inverseSurface = Color(0xFFE6E1E5)
val purple_dark_inverseOnSurface = Color(0xFF313033)
val purple_dark_inversePrimary = Color(0xFF6750A4)
val purple_dark_shadow = Color(0xFF000000)
val purple_dark_surfaceTint = Color(0xFFD0BCFF)
val purple_dark_outlineVariant = Color(0xFF49454F)
val purple_dark_scrim = Color(0xFF000000)


val purple_seed = Color(0xFF6750A4)
