package com.guilin.mycompose.ui.theme.color
import androidx.compose.ui.graphics.Color

val green_light_primary = Color(0xFF346A22)
val green_light_onPrimary = Color(0xFFFFFFFF)
val green_light_primaryContainer = Color(0xFFB5F39A)
val green_light_onPrimaryContainer = Color(0xFF042100)
val green_light_secondary = Color(0xFF54624D)
val green_light_onSecondary = Color(0xFFFFFFFF)
val green_light_secondaryContainer = Color(0xFFD8E7CC)
val green_light_onSecondaryContainer = Color(0xFF131F0E)
val green_light_tertiary = Color(0xFF386667)
val green_light_onTertiary = Color(0xFFFFFFFF)
val green_light_tertiaryContainer = Color(0xFFBCEBED)
val green_light_onTertiaryContainer = Color(0xFF002021)
val green_light_error = Color(0xFFBA1A1A)
val green_light_errorContainer = Color(0xFFFFDAD6)
val green_light_onError = Color(0xFFFFFFFF)
val green_light_onErrorContainer = Color(0xFF410002)
val green_light_background = Color(0xFFFDFDF6)
val green_light_onBackground = Color(0xFF1A1C18)
val green_light_surface = Color(0xFFFDFDF6)
val green_light_onSurface = Color(0xFF1A1C18)
val green_light_surfaceVariant = Color(0xFFDFE4D7)
val green_light_onSurfaceVariant = Color(0xFF43483F)
val green_light_outline = Color(0xFF73796E)
val green_light_inverseOnSurface = Color(0xFFF1F1EA)
val green_light_inverseSurface = Color(0xFF2F312D)
val green_light_inversePrimary = Color(0xFF9AD680)
val green_light_shadow = Color(0xFF000000)
val green_light_surfaceTint = Color(0xFF346A22)
val green_light_outlineVariant = Color(0xFFC3C8BB)
val green_light_scrim = Color(0xFF000000)

val green_dark_primary = Color(0xFF9AD680)
val green_dark_onPrimary = Color(0xFF0B3900)
val green_dark_primaryContainer = Color(0xFF1C520A)
val green_dark_onPrimaryContainer = Color(0xFFB5F39A)
val green_dark_secondary = Color(0xFFBCCBB0)
val green_dark_onSecondary = Color(0xFF273421)
val green_dark_secondaryContainer = Color(0xFF3D4B36)
val green_dark_onSecondaryContainer = Color(0xFFD8E7CC)
val green_dark_tertiary = Color(0xFFA0CFD1)
val green_dark_onTertiary = Color(0xFF003738)
val green_dark_tertiaryContainer = Color(0xFF1E4E4F)
val green_dark_onTertiaryContainer = Color(0xFFBCEBED)
val green_dark_error = Color(0xFFFFB4AB)
val green_dark_errorContainer = Color(0xFF93000A)
val green_dark_onError = Color(0xFF690005)
val green_dark_onErrorContainer = Color(0xFFFFDAD6)
val green_dark_background = Color(0xFF1A1C18)
val green_dark_onBackground = Color(0xFFE3E3DC)
val green_dark_surface = Color(0xFF1A1C18)
val green_dark_onSurface = Color(0xFFE3E3DC)
val green_dark_surfaceVariant = Color(0xFF43483F)
val green_dark_onSurfaceVariant = Color(0xFFC3C8BB)
val green_dark_outline = Color(0xFF8D9387)
val green_dark_inverseOnSurface = Color(0xFF1A1C18)
val green_dark_inverseSurface = Color(0xFFE3E3DC)
val green_dark_inversePrimary = Color(0xFF346A22)
val green_dark_shadow = Color(0xFF000000)
val green_dark_surfaceTint = Color(0xFF9AD680)
val green_dark_outlineVariant = Color(0xFF43483F)
val green_dark_scrim = Color(0xFF000000)


val green_seed = Color(0xFF356225)
